apiVersion: v2
name: caliber-infra-talk
version: 0.1.0
appVersion: '1.0.0'
description: A Helm chart for Kubernetes
engine: gotpl
dependencies:
  - name: my-nginx
    condition: my-nginx.enabled
    version: '0.1.0'
    repository: file://../../helm-demo/my-nginx
  - name: my-nginx2
    condition: my-nginx2.enabled
    version: '0.1.0'
    repository: file://../../helm-demo/my-nginx
