apiVersion: v2
name: caliber-infra-talk
version: 0.1.0
appVersion: '1.0.0'
description: A Helm chart for Kubernetes
engine: gotpl
dependencies:
  - name: my-nginx
    condition: my-nginx-1.enabled
    version: '0.1.0'
    repository: file://../../helm-demo/my-nginx
    alias: my-nginx-1
  - name: my-nginx
    condition: my-nginx-2.enabled
    version: '0.1.0'
    repository: file://../../helm-demo/my-nginx
    alias: my-nginx-2
