my-nginx-1:
  enabled: true

  replicaCount: 1

  image:
    tag: "1.25.2-alpine"

  envs:
    - name: DB_DSN
      value: <path:kv-v2/data/friendscan/prod#DB_DSN>?1
    - name: DB_DSN1
      value: <path:kv-v2/data/friendscan/prod#DB_DSN>?2
    - name: DB_DSN2
      value: <path:kv-v2/data/friendscan/prod#DEMO_ABC>?3

my-nginx-2:
  enabled: false

  replicaCount: 1

  image:
    tag: "1.25.2-alpine"

  envs:
    - name: DB_DSN
      value: <path:kv-v2/data/friendscan/prod#DB_DSN>?1
    - name: DB_DSN1
      value: <path:kv-v2/data/friendscan/prod#DB_DSN>?2
    - name: DB_DSN2
      value: <path:kv-v2/data/friendscan/prod#DEMO_ABC>?3

